name: Sync Tag with YAML Version
permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Extract Version from YAML
        id: get_version
        run: |
          VERSION=$(grep -oP '(?:version|VERSION):\s*"?\K[0-9]+\.[0-9]+\.[0-9]+' multiappproxy/config.yaml | head -n 1)

          if [ -z "$VERSION" ]; then
            echo "❌ Error: Version not found in multiappproxy/config.yaml"
            exit 1
          fi

          TAG="v$VERSION"

          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "✅ Version found: $TAG"

      - name: Push Tag
        run: |
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "⚠️  Tag $TAG already exists. Skipping."
          else
            echo "📌 Creating and pushing tag $TAG"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag $TAG
            git push origin $TAG
            echo "✅ Tag $TAG pushed successfully"
          fi
